Create README.md
1. install rabbitmq

http://blog.csdn.net/zcyzsy/article/details/53008269 (prepare for installing erlang)
http://www.erlang.org/download/otp_src_20.2.tar.gz 

http://www.linuxidc.com/Linux/2016-03/129557.htm (install rabbitmq)
http://www.rabbitmq.com/getstarted.html

http://blog.csdn.net/mx472756841/article/details/50733886 
ERROR: epmd error for host pascal: timeout (timed out)
 
2. introduce
http://www.rabbitmq.com/tutorials/tutorial-one-java.html